describe('Secret Menu with Cypress Studio', () => {
  beforeEach(() => {
    cy.visit('/secret-menu');
  });

  // cypress.json has to have
  // "experimentalStudio": true
  it('does stuff generated by Cypress Studio', () => {
    /* ==== Generated with Cypress Studio ==== */
    cy.get('#minimum-rating-visibility').click();
    cy.get('#restaurant-visibility-filter').select('Chick-fil-A');
    cy.get('[for="show-name"]').click();
    cy.get('#show-name').uncheck();
    cy.get('[for="show-secret"]').click();
    cy.get('#show-secret').uncheck();
    cy.get('[for="show-howToOrder"]').click();
    cy.get('#show-howToOrder').uncheck();
    cy.get('[for="show-ingredients"]').click();
    cy.get('#show-ingredients').uncheck();
    cy.get('#whereToOrder-column').click();
    cy.get('#minimum-rating-visibility').click();
    cy.get('#rating-visibility').click();
    /* ==== End Cypress Studio ==== */
  });
});
